### ISSUE TITLE
Built Docs

### ISSUE THREAD

**Issue by AjayAntoIsDev** [eggnaut/EggEngine#7]
make a new branch for docs (built ones) and host it using github-pages

https://github.com/AjayAntoIsDev/EggEngine/tree/site

**Comment by eggnaut** [comment]
I’ve never used Github Pages before, thanks for the idea! I’ll also use mkdocs :)

**Comment by eggnaut** [comment]
I've merged the docs from #6 into the main branch.

**Comment by eggnaut** [comment]
Lol I ended up deleting everything from the `docs` and `main` branch from your issue and #6 PR. Will add the docs back after breakfast.

**Comment by AjayAntoIsDev** [comment]
Hello you really dont need to learn any html to make docs its just markdown files that get built to html css and js file

**Comment by AjayAntoIsDev** [comment]
Also you didnt yet merged the docs

**Comment by eggnaut** [comment]
Oh that’s pretty cool.

As far as merging goes, I’ve merged the rest of the PR. I still want to think about docs and a doc site. This is currently a side project, I’m barely out pf middle school xD.

**Comment by AjayAntoIsDev** [comment]
Same I am just 12
